# Generated by Django 6.0.5 on 2026-05-06 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inimigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('floresta', 'Floresta'), ('caverna', 'Caverna'), ('castelo', 'Castelo')], max_length=20)),
                ('hp', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defesa', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('is_boss', models.BooleanField(default=False)),
                ('imagem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('consumivel', 'Consumivel')], max_length=100)),
                ('preco', models.IntegerField(default=0)),
                ('bonus_ataque', models.IntegerField(default=0)),
                ('bonus_defesa', models.IntegerField(default=0)),
                ('bonus_hp', models.IntegerField(default=0)),
                ('bonus_mp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(choices=[('guerreiro', 'Guerreiro'), ('mago', 'Mago'), ('ladrao', 'Ladrão'), ('arqueiro', 'Arqueiro')], max_length=20)),
                ('nivel', models.IntegerField(default=1)),
                ('experiencia', models.IntegerField(default=0)),
                ('hp_maximo', models.IntegerField(default=100)),
                ('hp_atual', models.IntegerField(default=100)),
                ('mp_maximo', models.IntegerField(default=50)),
                ('mp_atual', models.IntegerField(default=50)),
                ('ataque', models.IntegerField(default=10)),
                ('defesa', models.IntegerField(default=5)),
                ('gold', models.IntegerField(default=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.personagem')),
            ],
        ),
    ]
