# Generated by Django 6.0.5 on 2026-05-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='area_atual',
            field=models.CharField(choices=[('floresta', 'Floresta'), ('caverna', 'Caverna'), ('castelo', 'Castelo')], default='floresta', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personagem',
            name='area_desbloqueada',
            field=models.CharField(choices=[('floresta', 'Floresta'), ('caverna', 'Caverna'), ('castelo', 'Castelo')], default='floresta', max_length=20),
        ),
        migrations.AddField(
            model_name='personagem',
            name='batalhas_na_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='fugas_restantes',
            field=models.IntegerField(default=2),
        ),
    ]
