# Generated by Django 6.0.5 on 2026-05-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_personagem_area_atual_personagem_area_desbloqueada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='gold_salvo',
            field=models.IntegerField(default=0),
        ),
    ]
