# Generated by Django 6.0.5 on 2026-05-08 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_personagem_gold_salvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalha',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='batalha',
            name='inimigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.inimigo'),
        ),
        migrations.AddField(
            model_name='batalha',
            name='personagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.personagem'),
        ),
        migrations.AddField(
            model_name='batalha',
            name='resultado',
            field=models.CharField(choices=[('derrota', 'DERROTA'), ('vitoria', 'VITORIA'), ('fuga', 'FUGA')], max_length=10, null=True),
        ),
    ]
