# Generated by Django 6.0.5 on 2026-05-09 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_batalha_data_batalha_inimigo_batalha_personagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='arma_equipada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arma_equipada', to='game.item'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='armadura_equipada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armadura_equipada', to='game.item'),
        ),
    ]
