# Generated by Django 6.0.5 on 2026-05-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_personagem_arma_equipada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classes_permitidas',
            field=models.CharField(default='guerreiro,mago,ladrao,arqueiro', max_length=100),
        ),
    ]
