# Generated by Django 6.0.5 on 2026-05-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_item_classes_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inimigo',
            name='peso',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='classes_permitidas',
            field=models.CharField(default='guerreiro,mago,ladrao,arqueiro', help_text='Separe as classes por vírgula: guerreiro,mago,ladrao,arqueiro', max_length=100),
        ),
    ]
