# Generated by Django 6.0.5 on 2026-05-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_inimigo_peso_alter_item_classes_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inimigo',
            name='qtd_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inimigo',
            name='qtd_min',
            field=models.IntegerField(default=1),
        ),
    ]
