# Generated by Django 6.0.5 on 2026-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_inimigo_qtd_max_inimigo_qtd_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qtd_max',
            field=models.IntegerField(default=1),
        ),
    ]
