# Generated by Django 6.0.5 on 2026-05-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_item_qtd_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
